### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by gdude2002** [rhgrant10/Groupy#10]
Hey, I'm an owner of [a bot project named Ultros](https://ultros.io), a project that largely uses Twisted internally for all kinds of stuff. Naturally, Twisted hasn't yet been ported to Python 3, so I was wondering what the changes of a backport of Groupy to Python 2 are.

I noticed that this was a TODO, but I wanted to ask if there was any more info on this.

**Comment by rhgrant10** [comment]
Yeah it's on the table. I've just finished integrating the project with tox (running py34 and py35) and coverage, so the only thing that stands between this moment and 2.7 support is 100% test coverage. Hopefully writing all the tests goes quickly and I can move on to supporting more python versions. I've not tried running 3to2 on it... maybe that would go swimmingly, but maybe not.

I welcome any pull requests for either unit tests or compatibility improvements, but my focus right now is on the quality of what I've got.

**Comment by oatberry** [comment]
Has any progress been made on this? I'm really hoping to make a weechat script for groupme, but weechat doesn't support python3 by default. It can be enabled, but that breaks compatibility with python2 scripts.

**Comment by rhgrant10** [comment]
Hopefully I'll get around to this soon :)

**Comment by gdude2002** [comment]
Oh man, I totally forgot about this ticket.

For the record, we no longer need Python 2 support, and nobody should be seeking it - Python 3 is the future, baby!

**Comment by rhgrant10** [comment]
Haha glad to hear it!
