### ISSUE TITLE
Group.create does not create share_url

### ISSUE THREAD

**Issue by JCDJulian** [rhgrant10/Groupy#19]
I am able to create a group successfully using groupy.Group.create. However, even when share is set to True, the Group created is not shareable. Consequentially, the new group's share_url is None. I am able to set it manually in the app and retrieve the share_url. I've looked through the Groupy code and there doesn't seem to be anything wrong with the API request. This may be a problem on GroupMe's end.

**Comment by rhgrant10** [comment]
Yeah I'm experiencing the same issue... I'll see if groupme help chat folks
have any ideas.

**Comment by rhgrant10** [comment]
I've [posted my question](https://groups.google.com/forum/m/#!topic/groupme-api-support/DR1v7vc0upE) about the problem.

**Comment by rhgrant10** [comment]
I've still not heard anything regarding this issue. I've sent an email to their support team in the hopes that someone responds. As you say, I think I'm making the correct response, so it must be a server-side API issue, but regardless, I'm sorry you're having this issue. I'll keep you posted.

**Comment by tejassharma96** [comment]
Are there any updates on this? I've noticed that if you enable the option for sharing in the groupme web client on groupme.com, I can then access the share_url from groupy, but as stated above, creating a group using groupy doesn't allow me to share. Using group.update(share=True) doesn't do anything either.

**Comment by rhgrant10** [comment]
No unfortunately I'm afraid not. It's clearly a problem on their end but they don't seem eager to fix it. I've reached out to them via email and their support group but both attempts have largely been ignored. When they had a GroupMe group for API help their responsiveness was much better. I'd be happy to implement any necessary changes if anyone has success getting to the root of the issue.

**Comment by tejassharma96** [comment]
Oh ok, that's unfortunate :-(

**Comment by tejassharma96** [comment]
Ok, so I managed to get the update function working by changing the endpoints.Groups.update() function to this:

    data = {}
    if name:
        data['name'] = name
    if description:
        data['description'] = description
    if share is not None:
        data['share'] = share
    if image_url:
        data['image_url'] = image_url
    r = requests.post(
        cls.build_url('{}/update', group_id),
        data=json.dumps(data)
    )
    return cls.response(r)

Based on that, I think the problem is how the requests class was handling the params with a boolean. Not really sure if this helps, but since it feels really janky to me I'll probably just keep it in my local version and let you figure out what you want to do with it.

**Comment by rhgrant10** [comment]
This is fixed and tested in the new v0.8.0 available on PyPI :)
