### ISSUE TITLE
Comparing contents of a message

### ISSUE THREAD

**Issue by bunuble** [rhgrant10/Groupy#28]
```python
message = group.messages().newest
print(message.text) #printout is @user
print(message.text == "@user") #false
print(message.text is "@user") #false
```
Hopefully this library is still under development.

I'm trying to compare the contents of a message to a string. No matter what I try, the output is false. Any idea on how I should compare?

**Comment by rhgrant10** [comment]
Hey, hope you got this sorted out :)
