### ISSUE TITLE
ApiError crashing the bot

### ISSUE THREAD

**Issue by bunuble** [rhgrant10/Groupy#29]
So I am making a bot using your API wrapper and I tried using a try except to deal with the groupy.api.errors.ApiError but it still gets through and crashes the bot. Any way to deal with this?

**Comment by rhgrant10** [comment]
Can you show me the code you're running?

**Comment by bunuble** [comment]
```py
Traceback (most recent call last):
  File "ddgbot.py", line 45, in <module>
    mentions = active_group.messages().newest.attachments
  File "/usr/lib/python3.5/site-packages/groupy/object/responses.py", line 138, in messages
    raise e
  File "/usr/lib/python3.5/site-packages/groupy/object/responses.py", line 126, in messages
    since_id=since, after_id=after)
  File "/usr/lib/python3.5/site-packages/groupy/api/endpoint.py", line 303, in index
    return cls.response(r)
  File "/usr/lib/python3.5/site-packages/groupy/api/endpoint.py", line 73, in response
    raise errors.ApiError(data['meta'])
groupy.api.errors.ApiError: {'errors': ['read tcp 10.81.196.60:38811->10.79.182.137:22121: i/o timeout'], 'code': 500}
```

This is the Traceback

```
message = active_group.messages().newest
mentions = active_group.messages().newest.attachments
```

These are the two lines the error can happen. The line that causes it to happen is random.

I wrapped my code in this so I can see the error but the program won't crash
```py
try:
    [code]
except(KeyboardInterreupt,SystemExit)
    raise
except:
   [printing out error]
```

**Comment by rhgrant10** [comment]
Well, the API seems to be returning a 500 error, which is why the exception
is raised. It seems like you're able to catch the exception just fine...
what do you mean by "still gets through and crashes the bot?"

**Comment by bunuble** [comment]
It was a running process then it crashes. I check the output file and that was the last thing that happened before the process was terminated.

**Comment by rhgrant10** [comment]
Then it sounds like maybe you're not catching and handling the ApiErrors
that get raised. If you catch the exception then your process should not
crash.

**Comment by bunuble** [comment]
How would I catch that specific ApiError? I tried `except(groupy.api.erros.ApiError)` but I don't think that is right.

**Comment by rhgrant10** [comment]
That should be correct, although you don't need the parentheses. Just make
sure you're putting the try-except around the right code (there may be
multiple places, mind you).

**Comment by rhgrant10** [comment]
I just reread this thread top to bottom. It occurs to me that you may be raising the exception that you catch (judging by the naked raise in the except block in your second post). If that's the case, remove the raise from the except block and you should be good (as in the exception won't crash your bot).

**Comment by rhgrant10** [comment]
Did you ever get your issue resolved?

**Comment by bunuble** [comment]
Yes. Your advice helped. Thanks a lot!

**Comment by bunuble** [comment]
I got another quick question. What do I put so I can do something with generic attachments? Like for example, I can do `if m.type == 'image'`, I can have a conditional so i can do something with images. I tried `if m.type == 'GenericAttachment'` and `if m.type == 'genericattachment` but it is not working

**Comment by rhgrant10** [comment]
Sorry I'm just now reading this!

The idea of a `GenericAttachment` is that it's `type` attribute is something other than one of the currently known attachment types. So, for example, suppose next week they add the ability to have a video attachment. Well, all of a sudden their API is returning attachments with type "video" so until I wrote a `VideoAttachment` class it would simply be a `GenericAttachment` with a `type` attribute of "video". Hope that makes sense.

I'm going to close this issue now, but feel free to reach out with any questions you may have.
