### ISSUE TITLE
Mentions not serializing on Post method

### ISSUE THREAD

**Issue by a-vilmin** [rhgrant10/Groupy#31]
I created a mention as documented with the id/loci info, but when calling post(text, mentionObj), I get a "TyperError about Mentions(['123456']) is not JSON serializable". I have no problems posting regular text to the group. Am I using the attachments.Mentions object wrong?

**Comment by rhgrant10** [comment]
No it looks like this is actually a bug, so thanks for reporting it! I'll get to this as soon as I can but to be honest I don't have a lot of time to work on my personal projects much right now. However, I will gladly review and accept a PR for this and release the fixed version.

**Comment by rhgrant10** [comment]
I'll add that the fix is to call each attachments' `to_dict()` method before passing them on to the endpoints' `create()` method in the `groupy.object.responses.Recipient.post()` method.

**Comment by rhgrant10** [comment]
Aw wait a minute. I knew this seemed familiar. This is a duplicate of #30  and should've been fixed in v0.7.0 but I can't​ seem to see where it was actually fixed! I'll investigate further.

**Comment by rhgrant10** [comment]
Ah, found the problem. It was fixed but only for posting bot messages.

**Comment by rhgrant10** [comment]
Now available in v0.7.1 :)

**Comment by a-vilmin** [comment]
awesome thanks man!
