### ISSUE TITLE
API Key should not rely on global module-level variable

### ISSUE THREAD

**Issue by czue** [rhgrant10/Groupy#35]
Great library! Thanks for making it.

One issue is that if you want to build an app that allows users to provide their own API keys you can run into some thread safety issues by relying on the global `config.API_KEY` param for all API requests. In the worst case this could result in users seeing data they should not have had access to!

It would be great if there was a way to specify the API to use for any individual request to workaround this issue.

If you agree this would be a good change, I might be able to take a crack at implementing it.

**Comment by rhgrant10** [comment]
Thank you! Glad you find it useful!

And I completely agree. I've learned quite a lot about software development since I originally wrote this, and this is one of those things that seems quite obvious to me now - it should just be an argument to the client's initializer.

I would certainly welcome a PR :)

**Comment by czue** [comment]
Unfortunately, I just realized this library is GPL and that might mean I can't use it. But - I will definitely submit a PR if I come back to it!

**Comment by rhgrant10** [comment]
🙁 Well that's not something I've run into previously... why would you not be able to use GPL projects? What licenses would be okay or better and why?

**Comment by czue** [comment]
My understanding (might be wrong) is that anything I do on top of it under GPL has to also be open sourced, and I'm not sure the project I'm working on will be open sourced.

MIT, Apache, and LGPL are all more permissive. https://choosealicense.com/

**Comment by rhgrant10** [comment]
Oh, I see. Very interesting read, thank you!

**Comment by rhgrant10** [comment]
@czue you've inspired me, both to refactor the code base and to switch to the Apache license. If you're interested and willing, I can push it to a branch so you can give it a test drive. Keep in mind of course I haven't written docs or tests yet, but the code is short and simple.

**Comment by czue** [comment]
whoa, that's amazing, thanks! definitely happy to take it for a spin! would much rather use your lib than the hacky support i cobbled together. :smile:

**Comment by rhgrant10** [comment]
Awesome! Feel free to test the latest stuffs on the feature/rewrite branch. I'll be pushing the refactored code base to that branch. Let me know if you find any bugs or if you've got some sort of use case that isn't covered and I'll see what I can do.

**Comment by czue** [comment]
Hey - perfect timing, I was just getting ready to pick this project back up.

The new API seems great! I was able to accomplish everything I needed to from it. One tiny little thing was I had to access the group-level message summaries through `Group.data['messages']` because `messages` overrides the value from the raw API result, but that's totally workable.

Thanks for putting this together! Let me know if there's anything I can help with.

**Comment by czue** [comment]
(one thing I you will do is to just make sure you bump the version number so pip recognizes it as a new package.)

**Comment by Sebass13** [comment]
Wow, this is really convenient. I was thinking about submitting this as an issue when I first used Groupy in June, and now it's being addressed when I need to use it again.

**Comment by rhgrant10** [comment]
Sorry for the slow pace lately, been quite busy with a new job! Anyway, I think it's about ready to document and release. Let me know if you find any additional issues and I'll get this puppy out asap.

**Comment by rhgrant10** [comment]
Oops, I broke the `Attachment` class.... fix incoming.

**Comment by czue** [comment]
all good! i've been distracted by other things as well. really appreciate the incredible response / support on this!

**Comment by rhgrant10** [comment]
Finally got this done! You should be able to get v0.8.0 on PyPI now :)

**Comment by czue** [comment]
:clap: thanks!
