### ISSUE TITLE
Bots.post() doesn't work

### ISSUE THREAD

**Issue by ctv1337** [rhgrant10/Groupy#4]
Thanks so much for developing the Python groupyAPI! The below issue is using GroupyAPI version 58 on Windows 7 with Python 3.4

I'm attempting to post messages using the bots.post call but i'm getting an exception return as shown below. 

File "C:\Python34\lib\site-packages\groupy\object\responses.py", line 557, in
post
    except errors.InvalidResponse as e:
AttributeError: 'module' object has no attribute 'InvalidResponse'

The message will post to the group but the script dies after that. Any advice on debugging this? I've tried digging into responses.py but not quite sure i'm good enough at python to help. Thanks for your time.

**Comment by rhgrant10** [comment]
You are more than welcome! I'm sorry you're having problems.  I'm aware of the issue you're experiencing and a fix is on the way!

**Comment by rhgrant10** [comment]
This should be fixed in v0.6.1, now available on the PyPI. Please let me know if you're still experiencing any issues.

**Comment by ctv1337** [comment]
Now i'm getting the error below:
  File "C:\Python34\lib\site-packages\groupy\object\responses.py", line 591, in
post
    endpoint.Bot.post(self.bot_id, text, picture_url)
AttributeError: 'module' object has no attribute 'Bot'

If I change endpoint.Bot.post to endpoint.Bots.post I get the following error:
  File "C:\Python34\lib\site-packages\groupy\object\responses.py", line 593, in
post
    if e.args[0]['code'] != status.CREATED:
TypeError: 'Response' object is not subscriptable

**Comment by rhgrant10** [comment]
I've tested the bot functionality as much as possible right now without unit-tests in place. I can confirm that listing bots, posting messages with bots, and destroying bots all work. However, creating a bot was giving me an HTTP 500 error from the API, so I can't actually confirm that one at this time. Unit-tests are definitely next on the to-do list - obviously they should have been first ;-)

Release 0.6.2 has this fix. Thanks for the heads up on these issues.

**Comment by ctv1337** [comment]
Thanks for the fix. It works!

**Comment by rhgrant10** [comment]
Glad to hear!
