### ISSUE TITLE
Can't install even when Pillow is installed

### ISSUE THREAD

**Issue by igalfsg** [rhgrant10/Groupy#41]
I can't installed it even when pillow is already installed 
c:\users\igal\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\igal\\AppData\\Local\\Temp\\pip-build-l7ov0265\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\igal\AppData\Local\Temp\pip-rraf97nf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\igal\AppData\Local\Temp\pip-build-l7ov0265\Pillow\

**Comment by rhgrant10** [comment]
What command are you running? Also, just a heads up, I'm close to releasing a new version and one of the changes is I've dropped the dependency on pillow.

**Comment by igalfsg** [comment]
I did pip install GroupyAPI. but if you are releasing the fix soon I'll just wait it out :) thanks

**Comment by xac1d** [comment]
Same issue here. waiting for new version.

**Comment by rhgrant10** [comment]
@xac1d sorry to hear. I've just finished reverse-engineering the gallery endpoint so hopefully I can get this out the door by end of weekend.

Part of me is very curious why pip is trying to re-install a package when it's already installed. Not sure what would cause that.

**Comment by rhgrant10** [comment]
You should be able to get v0.8.0 on PyPI now. Now more Pillow dependency :)
