### ISSUE TITLE
Like comments in a group without conversation_id?

### ISSUE THREAD

**Issue by RidhwaanDev** [rhgrant10/Groupy#50]
I do not think the API supports liking a message in a group chat as it requires conversation_id which does not exists for group chats, only for direct messages.

Any help? I could be wrong.

**Comment by rhgrant10** [comment]
It does but the docs don't mention it. See https://github.com/rhgrant10/Groupy/blob/dev/groupy/api/messages.py#L297 and https://github.com/rhgrant10/Groupy/blob/dev/groupy/api/messages.py#L306

**Comment by RidhwaanDev** [comment]
Yeah I just figured out. They have to fix that. 

Have a good one.
