### ISSUE TITLE
Get 'likes' stats on a particular message

### ISSUE THREAD

**Issue by craig-cogdill** [rhgrant10/Groupy#51]
I read through the docs and didn't see anything like this, but is there any way to get things like the number of likes and which user IDs liked a message once I have a Message object?

**Comment by rhgrant10** [comment]
You can obtain that using the `favorited_by` field of a message. It contains the IDs of each user that has liked the message.

```python
>>> user_ids = message.favorited_by
>>> num_likes = len(message.favorited_by)
```

**Comment by craig-cogdill** [comment]
Thank you!
