### ISSUE TITLE
Issue with groups containing emoji in group name

### ISSUE THREAD

**Issue by johnluetz** [rhgrant10/Groupy#54]
When running
```python
for group in client.groups.list_all():
        print(group.name)
```
threw a `groupy.exceptions.InvalidJsonError: The JSON was incomplete/invalid`

Upon leaving all groups with emoji in the group name, the code runs as intended.

Python Version: 3.7.3
Groupy Version: 0.10.3
OS: Windows 10, Version 10.0.17134

**Comment by rhgrant10** [comment]
Sorry this is giving you trouble. It seems very similar to the known problem involving responses that exceed the max size... does it work if you omit the memberships field?

```client.groups.list_all(omit='memberships')```

**Comment by rhgrant10** [comment]
I tested this locally. I was able to create a group with an emoji in the name and then list all group names:

```>>> group_name = 
>>> group_name
'Emoji group name 👍'
>>> group = client.groups.create(name='Emoji group name 👍')
>>> group
<Group(name='Emoji group name 👍')>
>>> for g in client.groups.list_all():
...     print(g.name)
...
Emoji group name 👍
<snip>
>>>
```

@johnluetz is this still giving you issues?
